---
title: "Analyze_tfruns"
author: "Julin Maloof"
date: "12/7/2021"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(keras)
library(tfruns)
library(tidyverse)
```

```{r}
options(tfruns.runs_dir = "cats_dogs_tfruns_results/runs")
```

```{r}
View(ls_runs())
```

```{r}
view_run()
```

```{r}
compare_runs()
```

```{r}
runsdata <- ls_runs()
head(runsdata)
```

somehow my flags aren't there, but I can recreate those... 
```{r}
runsdata %>% arrange(desc(metric_val_acc)) %>%
  select(metric_val_acc, starts_with("flag"))
```

```{r}
runsdata %>% 
  select(metric_val_acc, starts_with("flag")) %>%
  mutate(flag_four_layer = factor(
    ifelse(flag_four_layer, "four conv layers", "three conv layers"),
    levels=c("three conv layers", "four conv layers"))) %>%
  ggplot(aes(y=metric_val_acc, x=as.factor(flag_filters), fill=as.factor(flag_kernel))) +
  geom_col(position="dodge") +
  facet_grid(flag_four_layer ~ flag_dropout)
```

Let's compare best run to original

```{r}
runsdata %>% filter(metric_val_acc == max(metric_val_acc) |
                      (flag_four_layer==TRUE & flag_dropout==0.5 & flag_filters==32 & flag_kernel==3)) %>%
  pull(run_dir) %>%
  basename() %>%
  magrittr::extract(1:2) %>%
  compare_runs()


```

