---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(keras)
```

```{r}
chr1 <- read_csv("AtSeqs/chr1_1hot.csv.gz") %>%
  select(-pos) %>%
  data.matrix()

head(chr1)
```

modify to pull sequence from both back and forwards
```{r}
generator <- function(data, window, delay=0, min_index, max_index,
                      shuffle = FALSE, batch_size = 32, step = 1) { #note window is really half window
  if (is.null(max_index))
    max_index <- nrow(data) - delay - window - 1
  i <- min_index + window
  function() {
    if (shuffle) {
      rows <- sample(c((min_index+window):max_index), size = batch_size)
    } else {
      if (i + batch_size >= max_index)
        i <<- min_index + window
      rows <- c(i:min(i+batch_size, max_index))
      i <<- i + length(rows)
    }
    
    samples <- array(0, dim = c(length(rows), 
                                window / step,
                                2* (dim(data)[[-1]]-1))) # don't include CDS in samples, do include data from forward and backwards
    targets <- array(0, dim = c(length(rows)))
                     
    for (j in 1:length(rows)) {
      indices.bak <- seq(rows[[j]] - window + 1, rows[[j]],  #why do I need +1?  error in original?
                     length.out = dim(samples)[[2]])
      indices.for <- indices.bak+window
      # indices.bak go from -window to the focal position
      # indices.for for from (1+the focal position) to (1+focal+window)
      
      #now each row of samples has data from before and after the focal base, getting progressively further away
      samples[j,,] <- cbind(data[indices.bak, -1 ], # -1 = don't include CDS in samples
                            data[indices.for, -1 ])
      
      targets[[j]] <- data[rows[[j]] + delay,1]
    }            
    
    list(samples, targets)
  }
}
```

```{r}
nrow(chr1) # 30427671
lookback <- 400
step <- 1
delay <- 0
batch_size <- 128

train_gen <- generator(
  data,
  lookback = lookback,
  delay = delay,
  min_index = 1,
  max_index = 5000000,
  shuffle = TRUE,
  step = step, 
  batch_size = batch_size
)

val_gen = generator(
  data,
  lookback = lookback,
  delay = delay,
  min_index = 5000001,
  max_index = 6000000,
  step = step,
  batch_size = batch_size
)

test_gen <- generator(
  data,
  lookback = lookback,
  delay = delay,
  min_index = 6000001,
  max_index = 7000000,
  step = step,
  batch_size = batch_size
)

# This is how many steps to draw from `val_gen`
# in order to see the whole validation set:
val_steps <- (6000000 - 5000001 - lookback) / batch_size

  # This is how many steps to draw from `test_gen`
# in order to see the whole test set:
test_steps <- (7000000 - 6000001 - lookback) / batch_size
```
