---
title: "Chapter 3"
author: "Julin Maloof"
date: "1/11/2021"
output: html_document
---

```{r}
library(keras)
library(reticulate)
use_condaenv("r-reticulate")
```

set up python environment, only has to be done once NOT WORKING
```{r, eval=FALSE}
virtualenv_remove("r-python3.8")
virtualenv_create("r-python3.8", python="/usr/local/opt/python@3.8/bin/python3")
```

NOTWORKING
```{r, eval=FALSE}
use_virtualenv("r-python3.8")
install_keras(method="virtualenv", envname="r-python3.8")
```

GIVING UP AND TRYING CONDA METHOD

```{r, eval=FALSE}
conda_create(packages="python=3.6")
use_condaenv("r-reticulate")
install_keras(method="conda", envname="r-reticulate")
```


## Reuters data set

get the data
```{r}
reuters <- dataset_reuters(num_words = 10000)
c(c(train_data, train_labels), c(test_data, test_labels)) %<-% reuters
```

```{r}
length(train_data)
length(test_data)
```

vectorize data
```{r}
vectorize_sequences <- function(sequences, dimension = 10000) {
  results <- matrix(0, nrow = length(sequences), ncol = dimension)
  for (i in 1:length(sequences))
    results[i, sequences[[i]]] <- 1
  results
}

x_train <- vectorize_sequences(train_data)            
x_test <- vectorize_sequences(test_data)              
```

vectorize labels
```{r}
one_hot_train_labels <- to_categorical(train_labels)
one_hot_test_labels <- to_categorical(test_labels)
```

model
```{r}
model <- keras_model_sequential() %>%
  layer_dense(units = 64, activation = "relu", input_shape = c(10000)) %>%
  layer_dense(units = 64, activation = "relu") %>%
  layer_dense(units = 46, activation = "softmax")
```

```{r}
model %>% compile(
  optimizer = "rmsprop",
  loss = "categorical_crossentropy",
  metrics = c("accuracy")
)
```

validation set:
```{r}
val_indices <- 1:1000

x_val <- x_train[val_indices,]
partial_x_train <- x_train[-val_indices,]

y_val <- one_hot_train_labels[val_indices,]
partial_y_train = one_hot_train_labels[-val_indices,]
```

run it
```{r}
system.time(
  history <- model %>% fit(
  partial_x_train,
  partial_y_train,
  epochs = 20,
  batch_size = 512,
  validation_data = list(x_val, y_val)
)
)
```

```{r}
plot(history)
```
retrain
```{r}
model <- keras_model_sequential() %>%
  layer_dense(units = 64, activation = "relu", input_shape = c(10000)) %>%
  layer_dense(units = 64, activation = "relu") %>%
  layer_dense(units = 46, activation = "softmax")

model %>% compile(
  optimizer = "rmsprop",
  loss = "categorical_crossentropy",
  metrics = c("accuracy")
)

history <- model %>% fit(
  partial_x_train,
  partial_y_train,
  epochs = 9,
  batch_size = 512,
  validation_data = list(x_val, y_val)
)

results <- model %>% evaluate(x_test, one_hot_test_labels)
```

```{r}
 results
```

