---
title: "InstallMacTensorflow"
author: "Julin Maloof"
date: "1/13/2021"
output: html_document
---

There is a new optimized tensor flow available for Mac OS11

```{bash, eval=FALSE}
# run this in an actual terminal because it is interactive
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/apple/tensorflow_macos/master/scripts/download_and_install.sh)"
# then copy over the file from the tmp directory to ~/bin in case you want to reuse it.
```


```{bash}
cd
rm -rf /Users/jmaloof/.virtualenvs/tensorflow_macos_venv/
~/bin/tensorflow_macos/install_venv.sh --python=/usr/local/opt/python@3.8/bin/python3 -y /Users/jmaloof/.virtualenvs/tensorflow_macos_venv/

. "/Users/jmaloof/.virtualenvs/tensorflow_macos_venv/bin/activate"

pip install keras 
pip install h5py pyyaml requests Pillow scipy
```

```{r}
library(keras)
library(reticulate)
use_virtualenv("~/.virtualenvs/tensorflow_macos_venv/", required = TRUE )
py_module_available("tensorflow") 
library(tensorflow)
```


```{r}
py_config()
```

```{r}
dataset <- dataset_boston_housing()

```

